package com.eduvation.lufthansa.APIObjects.Countries;

public class CountryList {
    static Country[] countries = {
            new Country("AE", "United Arab Emirates"),
            new Country("AL", "Albania"),
            new Country("AR", "Argentina"),
            new Country("AT", "Austria"),
            new Country("AZ", "Azerbaijan"),
            new Country("BA", "Bosnia and Herzegovina"),
            new Country("BE", "Belgium"),
            new Country("BG", "Bulgaria"),
            new Country("BY", "Belarus"),
            new Country("CA", "Canada"),
            new Country("CH", "Switzerland"),
            new Country("CN", "China"),
            new Country("CO", "Colombia"),
            new Country("CR", "Costa Rica"),
            new Country("CY", "Cyprus"),
            new Country("CZ", "Czech Republic"),
            new Country("DE", "Germany"),
            new Country("DK", "Denmark"),
            new Country("DZ", "Algeria"),
            new Country("EE", "Estonia"),
            new Country("EG", "Egypt"),
            new Country("ES", "Spain"),
            new Country("ET", "Ethiopia"),
            new Country("FI", "Finland"),
            new Country("FR", "France"),
            new Country("GB", "United Kingdom"),
            new Country("GE", "Georgia"),
            new Country("GH", "Ghana"),
            new Country("GR", "Greece"),
            new Country("HR", "Croatia"),
            new Country("HU", "Hungary"),
            new Country("ID", "Indonesia"),
            new Country("IE", "Ireland"),
            new Country("IL", "Israel"),
            new Country("IN", "India"),
            new Country("IR", "Iran"),
            new Country("IS", "Island"),
            new Country("IT", "Italy"),
            new Country("JO", "Jordan"),
            new Country("JP", "Japan"),
            new Country("KR", "Korean Republic"),
            new Country("KW", "Kuwait"),
            new Country("KZ", "Kazakhstan"),
            new Country("LB", "Lebanon"),
            new Country("LT", "Lithuania"),
            new Country("LU", "Luxemburg"),
            new Country("LV", "Latvia"),
            new Country("MA", "Morocco"),
            new Country("MD", "Moldova Republic"),
            new Country("ME", "Montenegro"),
            new Country("MT", "Malta"),
            new Country("MU", "Mauritius"),
            new Country("MX", "Mexico"),
            new Country("MY", "Malaysia"),
            new Country("NG", "Nigeria"),
            new Country("NL", "Netherlands"),
            new Country("NO", "Norway"),
            new Country("OM", "Oman"),
            new Country("PA", "Panama"),
            new Country("PL", "Poland"),
            new Country("PT", "Portugal"),
            new Country("QA", "Qatar"),
            new Country("RO", "Romania"),
            new Country("RS", "Serbia"),
            new Country("RU", "Russia"),
            new Country("SA", "Saudi Arabia"),
            new Country("SE", "Sweden"),
            new Country("SG", "Singapore"),
            new Country("SI", "Slovenia"),
            new Country("TH", "Thailand"),
            new Country("TR", "Turkey"),
            new Country("TU", "Tunisia"),
            new Country("UA", "Ukraine"),
            new Country("US", "United States"),
            new Country("VE", "Venezuela"),
            new Country("VN", "Vietnam"),
            new Country("XK", "Kosovo"),
            new Country("ZA", "South Africa")
    };
}
